name: Build SukiSU

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - guacamole
          - guacamoleb
          - sm8150  # OnePlus 7 Pro (add support)
        kernel_path:
          - "android_kernel_oneplus_sm8150"
        anykernel_path:
          - "AnyKernel3"
    steps:
      - name: Checkout SukiSU repo
        uses: actions/checkout@v3
        with:
          path: SukiSU

      - name: Checkout device kernel
        uses: actions/checkout@v3
        with:
          repository: LineageOS/android_kernel_oneplus_sm8150
          path: ${{ matrix.kernel_path }}

      - name: Checkout AnyKernel3
        uses: actions/checkout@v3
        with:
          repository: osm0sis/AnyKernel3
          path: ${{ matrix.anykernel_path }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Build SukiSU for ${{ matrix.device }}
        run: |
          cd SukiSU
          ./gradlew assembleRelease -Pdevice=${{ matrix.device }}

      - name: Build kernel for ${{ matrix.device }}
        run: |
          cd ${{ matrix.kernel_path }}
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make O=out ${{ matrix.device }}_defconfig
          make -j$(nproc) O=out

      - name: Prepare AnyKernel3 for ${{ matrix.device }}
        run: |
          cp ${{ matrix.kernel_path }}/out/arch/arm64/boot/Image.gz-dtb ${{ matrix.anykernel_path }}
          cd ${{ matrix.anykernel_path }}
          zip -r ../${{ matrix.device }}-kernel.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.device }}-build
          path: |
            SukiSU/app/build/outputs/**/*.apk
            */*-kernel.zip
