name: Build OnePlus_SukiSU Ultra All
on:
  workflow_dispatch:
    inputs:
      CPU:
        type: choice
        description: "Branch"
        required: true
        default: sm8550
        options:
          - sm7550
          - sm7675
          - sm8150
          - sm8450
          - sm8475
          - sm8550
      FEIL:
        type: string
        description: "FEIL name"
        required: true
        default: SU
      CONFIG:
        type: choice
        description: "Configuration file"
        required: true
        default: oneplus_ace2pro_v
        options:
          - oneplus_nord_ce4_v
          - oneplus_ace_3v_v
          - oneplus_nord_4_v
          - oneplus_10_pro_v
          - oneplus_10t_v
          - oneplus_11r_v
          - oneplus_ace2_v
          - oneplus_ace_pro_v
          - oneplus_11_v
          - oneplus_12r_v
          - oneplus_ace2pro_v
          - oneplus_ace3_v
          - oneplus_7pro_v  # Added support for OnePlus 7 Pro (codename: guacamolep)
          - oneplus_open_v
          - oneplus12_v
          - oneplus_13r
          - oneplus_ace3_pro_v
          - oneplus_ace5
          - oneplus_pad2_v
          - oneplus_13
          - oneplus_13t
          - oneplus_ace5_pro
          - GitHub may have a bug that prevents the last option from appearing; use this placeholder
      KERNEL_VERSION:
        type: choice
        description: "Kernel version"
        required: true
        default: "5.15"
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
      BUILD_METHOD:
        type: choice
        description: "Build method"
        required: true
        default: "AnyKernel3"
        options:
          - "anykernel3"
          - "twrp"
env:
  KSUVER: SU
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update && sudo apt-get install -y bc bison flex libssl-dev

      - name: Configure build variables
        run: |
          CPU="${{ github.event.inputs.CPU }}"
          FEIL="${{ github.event.inputs.FEIL }}"
          CONFIG="${{ github.event.inputs.CONFIG }}"
          KVER="${{ github.event.inputs.KERNEL_VERSION }}"
          METHOD="${{ github.event.inputs.BUILD_METHOD }}"
          echo "CPU=$CPU" >> $GITHUB_ENV
          echo "FEIL=$FEIL" >> $GITHUB_ENV
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          echo "KVER=$KVER" >> $GITHUB_ENV
          echo "METHOD=$METHOD" >> $GITHUB_ENV

      - name: Build kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          case "$CONFIG" in
            oneplus_7pro_v)
              DEFCONFIG=guacamolep_defconfig ;;  # OnePlus 7 Pro codename: guacamolep
            *)
              DEFCONFIG="${CONFIG}_defconfig" ;;
          esac
          make O=out ${DEFCONFIG}
          make -j$(nproc) O=out

      - name: Package
        run: |
          KSU_OUT=out/arch/arm64/boot/Image.gz-dtb
          cp $KSU_OUT SU-${CONFIG}-${CPU}.img

      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: SU-${{ env.CONFIG }}-${{ env.CPU }}.img
          path: SU-${{ env.CONFIG }}-${{ env.CPU }}.img
